with open("app/scheduler/engine.py", "r") as f:
    text = f.read()
text = text.replace("            batch_val = ", "                batch_val = ")
text = text.replace("            if not batch_val.satisfied:", "                if not batch_val.satisfied:")
text = text.replace('            error_counts["Batch Quantity"] = ', '                error_counts["Batch Quantity"] = ')
text = text.replace("            assignments.append(", "                assignments.append(")
text = text.replace("            AssignmentProposal(", "                AssignmentProposal(")
text = text.replace('            assignment_id=f"ASG-{order.order_id}-{routing_op.sequence}",', '                assignment_id=f"ASG-{order.order_id}-{routing_op.sequence}",')
text = text.replace("            order_id=order.order_id, routing_id=routing_op.routing_id,", "                order_id=order.order_id, routing_id=routing_op.routing_id,")
text = text.replace("            sequence=routing_op.sequence, operation_name=routing_op.operation_name,", "                sequence=routing_op.sequence, operation_name=routing_op.operation_name,")
text = text.replace("            machine_id=None, operator_id=None,", "                machine_id=None, operator_id=None,")
text = text.replace("            start_time=date_range_start, end_time=date_range_start,", "                start_time=date_range_start, end_time=date_range_start,")
text = text.replace("            setup_start_time=None, changeover_minutes=0,", "                setup_start_time=None, changeover_minutes=0,")
text = text.replace("            duration_minutes=routing_op.duration_minutes,", "                duration_minutes=routing_op.duration_minutes,")
text = text.replace('            tool_ids=[], material_allocations={}, status="infeasible",', '                tool_ids=[], material_allocations={}, status="infeasible",')
text = text.replace('            constraint_violations=[f"H12: {batch_val.message}"]', '                constraint_violations=[f"H12: {batch_val.message}"]')
text = text.replace("        )", "                )")
text = text.replace("    )", "                )")
text = text.replace("    continue", "                continue")
with open("app/scheduler/engine.py", "w") as f:
    f.write(text)
